-d C:\Users\slg\WorkSpace\TangPrimer-25K\LicheeTang25k_VexRV_micro\gw_vex\impl\gwsynthesis\gw_vex.vg
-p GW5A-25A-MBGA121N-1
-pn GW5A-LV25MG121NC1/I0
-cst C:\Users\slg\WorkSpace\TangPrimer-25K\LicheeTang25k_VexRV_micro\gw_vex\src\gw_vex.cst
-cfg C:\Users\slg\WorkSpace\TangPrimer-25K\LicheeTang25k_VexRV_micro\gw_vex\impl\pnr\device.cfg
-sdc C:\Users\slg\WorkSpace\TangPrimer-25K\LicheeTang25k_VexRV_micro\gw_vex\src\gw_vex.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
